/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef __cplusplus
extern "C" {
#endif

GtkWidget* create_window (void);
GtkWidget* create_fileselection (void);

#ifdef __cplusplus
}
#endif
