import argparse
import csv
from collections import defaultdict
from pathlib import Path

import torch
import torch.optim as optim

from grounding_dino_finetune_utils import (
    default_model_config_path,
    default_model_weights_path,
    load_image,
    load_model,
    train_image,
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Fine-tune GroundingDINO on a CSV annotation file."
    )
    parser.add_argument(
        "--config",
        default=default_model_config_path(),
        help="Path to the GroundingDINO model config.",
    )
    parser.add_argument(
        "--weights",
        default=default_model_weights_path(),
        help="Path to the pretrained GroundingDINO weights.",
    )
    parser.add_argument(
        "--image-dir",
        default="train/images",
        help="Directory containing the training images referenced by the CSV file.",
    )
    parser.add_argument(
        "--annotations",
        default="train/annotations_final.csv",
        help="CSV file generated by create_annotations_final.py.",
    )
    parser.add_argument("--epochs", type=int, default=50, help="Number of training epochs.")
    parser.add_argument(
        "--save-dir",
        default="weights_less",
        help="Directory where fine-tuned checkpoints will be saved.",
    )
    parser.add_argument(
        "--save-every",
        type=int,
        default=5,
        help="Save a checkpoint every N epochs.",
    )
    parser.add_argument("--lr", type=float, default=1e-5, help="Learning rate.")
    parser.add_argument(
        "--device",
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Computation device for fine-tuning.",
    )
    return parser.parse_args()


def read_dataset(annotation_file: Path, image_dir: Path):
    annotation_dict = defaultdict(lambda: defaultdict(list))
    with annotation_file.open() as file_obj:
        ann_reader = csv.DictReader(file_obj)
        for row in ann_reader:
            image_path = image_dir / row["image_name"]
            annotation_dict[image_path]["boxes"].append(
                [
                    int(row["bbox_x1"]),
                    int(row["bbox_y1"]),
                    int(row["bbox_x2"]),
                    int(row["bbox_y2"]),
                ]
            )
            annotation_dict[image_path]["captions"].append(row["label_name"])
    return annotation_dict


def train(model, annotation_file: Path, image_dir: Path, epochs=1, save_dir=Path("weights_less"), save_every=5, lr=1e-5, device="cpu"):
    annotation_dict = read_dataset(annotation_file, image_dir)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    model.train()
    save_dir.mkdir(parents=True, exist_ok=True)

    for epoch in range(epochs):
        total_loss = 0.0
        for idx, (image_path, values) in enumerate(annotation_dict.items(), start=1):
            image_source, image = load_image(str(image_path))

            optimizer.zero_grad()
            loss = train_image(
                model=model,
                image_source=image_source,                                                                                                                                              
                image=image,
                caption_objects=values["captions"],
                box_target=values["boxes"],
                device=device,
            )
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            print(f"Processed image {idx}/{len(annotation_dict)}, Loss: {loss.item():.4f}")

        average_loss = total_loss / max(len(annotation_dict), 1)
        print(f"Epoch {epoch + 1}/{epochs}, Average Loss: {average_loss:.4f}")
        if (epoch + 1) % save_every == 0 or epoch == epochs - 1:
            checkpoint_path = save_dir / f"model_weights_epoch_{epoch + 1}.pth"
            torch.save(
                {
                    "model": model.state_dict(),
                    "epoch": epoch + 1,
                },
                checkpoint_path,
            )
            print(f"Model weights saved to {checkpoint_path}")


if __name__ == "__main__":
    args = parse_args()
    model = load_model(args.config, args.weights, device=args.device)
    train(
        model=model,
        annotation_file=Path(args.annotations),
        image_dir=Path(args.image_dir),
        epochs=args.epochs,
        save_dir=Path(args.save_dir),
        save_every=args.save_every,
        lr=args.lr,
        device=args.device,
    )
