on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cppbuild:
    runs-on: ubuntu-latest
    container: asmorkalov/learnopnecv_ci
    steps:
      - run: ./build_all.sh
